### create
POST http://localhost:9000/user
Content-Type: application/json

{
  "username": "test1",
  "password": "1",
  "email": "ananas@gmail.com"
}

### get
GET http://localhost:9000/user/1

### delete
DELETE http://localhost:9000/user/52

### update
PUT http://localhost:9000/user
Content-Type: application/json

{
  "id": 52,
  "username": "aboba",
  "password": "22222",
  "email": "ananas@yandex.ru"
}

### login
POST http://localhost:9000/user
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; username = test1; password = 1