server:
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diplom-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
application:
  allowed:
    methods: "POST,GET,PUT,DELETE"
    origins: "http://localhost:3000,http://localhost:3001"
  jwt:
    secretKey: оченьсекретныйпароль
    tokenPrefix: Bearer.
    tokenExpiration: 100